language: cpp
sudo: false

matrix:
  include :
    - os: linux
      compiler: gcc
      addons:
          packages:
              valgrind
              cppcheck
              gcov
      script: 
          - g++ -std=c++0x Print/help.cpp Print/print_matrix.cpp Row/row_op.cpp Column/column_op.cpp matrix-main.cpp -o matrix_elementary_operations
          - ./matrix_elementary_operations
          - gcov Print/help.cpp Print/print_matrix.cpp Row/row_op.cpp Column/column_op.cpp matrix-main.cpp 
          - cppcheck
