language: cpp
sudo: false

matrix:
  include :
    - os: linux
      compiler: gcc
      install:
          - sudo apt-get install -qq cppcheck
      script: 
          - g++ -std=c++1z Print/help.cpp Print/print_matrix.cpp Row/row_op.cpp Column/column_op.cpp matrix-main.cpp -o matrix_elementary_operations
          - ./matrix_elementary_operations -h
          - cppcheck .
